//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bodega
    {
        public Bodega()
        {
            this.ProductoInventarios = new HashSet<ProductoInventario>();
        }
    
        public int CodigoBodega { get; set; }
        public int CodigoSucursal { get; set; }
        public int CodigoEmpresa { get; set; }
        public string Nombre { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<ProductoInventario> ProductoInventarios { get; set; }
    }
}
