//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClienteTipo
    {
        public ClienteTipo()
        {
            this.Clientes = new HashSet<Cliente>();
            this.ProductoPrecios = new HashSet<ProductoPrecio>();
        }
    
        public int CodigoClienteTipo { get; set; }
        public int CodigoEmpresa { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<ProductoPrecio> ProductoPrecios { get; set; }
    }
}
