//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Facturas = new HashSet<Factura>();
        }
    
        public int CodigoCliente { get; set; }
        public int CodigoEmpresa { get; set; }
        public string Identificador { get; set; }
        public string NombreComercial { get; set; }
        public string Area { get; set; }
        public string Telefono { get; set; }
        public string Direccion { get; set; }
        public string CorreoElectronico { get; set; }
        public bool PoseeCredito { get; set; }
        public Nullable<System.DateTime> FechaCorte { get; set; }
        public Nullable<int> DiasCreditos { get; set; }
        public decimal MontoPermitido { get; set; }
    
        public virtual ICollection<Factura> Facturas { get; set; }
    }
}
