//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaDetalle
    {
        public int CodigoFacturaDetalle { get; set; }
        public Nullable<int> CodigoFactura { get; set; }
        public Nullable<long> Numero { get; set; }
        public string Serie { get; set; }
        public Nullable<int> CodigoSucursal { get; set; }
        public Nullable<int> CodigoEmpresa { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<int> CodigoProducto { get; set; }
        public Nullable<int> PrecioUnitario { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
