//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        public Factura()
        {
            this.FacturaDetalles = new HashSet<FacturaDetalle>();
            this.FacturaMetodoPagoes = new HashSet<FacturaMetodoPago>();
        }
    
        public int CodigoFactura { get; set; }
        public long Numero { get; set; }
        public string Serie { get; set; }
        public int CodigoSucursal { get; set; }
        public int CodigoEmpresa { get; set; }
        public int CodigoCliente { get; set; }
        public string FechaCreacion { get; set; }
        public string Cae { get; set; }
        public string Face { get; set; }
        public string UserId { get; set; }
        public int CodigoFacturaTipo { get; set; }
        public decimal Iva { get; set; }
        public decimal MontoNeto { get; set; }
        public decimal MontoBruto { get; set; }
        public int CodigoFacturaEstado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual FacturaEstado FacturaEstado { get; set; }
        public virtual FacturaTipo FacturaTipo { get; set; }
        public virtual Sucursal Sucursal { get; set; }
        public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; }
        public virtual ICollection<FacturaMetodoPago> FacturaMetodoPagoes { get; set; }
    }
}
