//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MetodoPago
    {
        public MetodoPago()
        {
            this.FacturaMetodoPagoes = new HashSet<FacturaMetodoPago>();
        }
    
        public int CodigoMetodoPago { get; set; }
        public int CodigoEmpresa { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<FacturaMetodoPago> FacturaMetodoPagoes { get; set; }
    }
}
