//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenCompraDetalle
    {
        public int CodigoOrdenCompraDetalle { get; set; }
        public int CodigoOrdenCompra { get; set; }
        public int CodigoSucursal { get; set; }
        public int CodigoEmpresa { get; set; }
        public int CodigoProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> PrecioEsperado { get; set; }
    
        public virtual OrdenCompra OrdenCompra { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
