//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        public Pedido()
        {
            this.PedidoDetalles = new HashSet<PedidoDetalle>();
        }
    
        public int CodigoPedido { get; set; }
        public int CodigoSucursal { get; set; }
        public int CodigoEmpresa { get; set; }
        public Nullable<int> CodigoPedidoLocal { get; set; }
        public int FechaCreacion { get; set; }
        public string UserId { get; set; }
    
        public virtual ICollection<PedidoDetalle> PedidoDetalles { get; set; }
    }
}
