//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoClasificacion
    {
        public ProductoClasificacion()
        {
            this.Productoes = new HashSet<Producto>();
            this.ProductoClasificacion1 = new HashSet<ProductoClasificacion>();
        }
    
        public int CodigoProductoClasificacion { get; set; }
        public int CodigoEmpresa { get; set; }
        public Nullable<int> CodigoClasificacionPadre { get; set; }
        public string Descripcion { get; set; }
        public bool Estado { get; set; }
    
        public virtual ICollection<Producto> Productoes { get; set; }
        public virtual ICollection<ProductoClasificacion> ProductoClasificacion1 { get; set; }
        public virtual ProductoClasificacion ProductoClasificacion2 { get; set; }
    }
}
