//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.FacturaDetalles = new HashSet<FacturaDetalle>();
        }
    
        public int CodigoProducto { get; set; }
        public int CodigoEmpresa { get; set; }
        public Nullable<int> CodigoClasificacion { get; set; }
        public string CodigoLocal { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CodigoProductoTipo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> PrecioCosto { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<bool> Estado { get; set; }
    
        public virtual ICollection<FacturaDetalle> FacturaDetalles { get; set; }
        public virtual ProductoTipo ProductoTipo { get; set; }
    }
}
