//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APITest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.ProductoPrecios = new HashSet<ProductoPrecio>();
            this.ProductoImagens = new HashSet<ProductoImagen>();
            this.ProductoInventarios = new HashSet<ProductoInventario>();
            this.OrdenCompraDetalles = new HashSet<OrdenCompraDetalle>();
            this.ProductoAPedirs = new HashSet<ProductoAPedir>();
            this.PedidoDetalles = new HashSet<PedidoDetalle>();
        }
    
        public int CodigoProducto { get; set; }
        public int CodigoEmpresa { get; set; }
        public Nullable<int> CodigoProductoClasificacion { get; set; }
        public Nullable<int> CodigoProductoMarca { get; set; }
        public string CodigoLocal { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> CodigoProductoTipo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> PrecioCosto { get; set; }
        public Nullable<decimal> PrecioVenta { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string SKU { get; set; }
        public Nullable<int> CodigoProductoAbastecimiento { get; set; }
        public Nullable<int> StockMinimo { get; set; }
        public Nullable<decimal> Alto { get; set; }
        public Nullable<decimal> Ancho { get; set; }
        public Nullable<decimal> Profundidad { get; set; }
        public string ImagenUrl { get; set; }
        public Nullable<int> CodigoProductoSubClasificacion { get; set; }
    
        public virtual ProductoClasificacion ProductoClasificacion { get; set; }
        public virtual ProductoMarca ProductoMarca { get; set; }
        public virtual ProductoTipo ProductoTipo { get; set; }
        public virtual ProductoAbastecimiento ProductoAbastecimiento { get; set; }
        public virtual ICollection<ProductoPrecio> ProductoPrecios { get; set; }
        public virtual ICollection<ProductoImagen> ProductoImagens { get; set; }
        public virtual ICollection<ProductoInventario> ProductoInventarios { get; set; }
        public virtual ProductoSubClasificacion ProductoSubClasificacion { get; set; }
        public virtual ICollection<OrdenCompraDetalle> OrdenCompraDetalles { get; set; }
        public virtual ICollection<ProductoAPedir> ProductoAPedirs { get; set; }
        public virtual ICollection<PedidoDetalle> PedidoDetalles { get; set; }
    }
}
